Repository TaskSprints/auction, pull requests merged in 2024-10, with the labels that each got.

#50 [FEATURE] - 최신 순, 조회수 순 정렬 구현 및 페이징 처리
  src/main/java/com/tasksprints/auction/api/auction/AuctionController.java
  src/main/java/com/tasksprints/auction/domain/auction/dto/response/AuctionResponse.java
  src/main/java/com/tasksprints/auction/domain/auction/model/Auction.java
  src/main/java/com/tasksprints/auction/domain/auction/model/AuctionCategory.java
  src/main/java/com/tasksprints/auction/domain/auction/model/AuctionStatus.java
  src/main/java/com/tasksprints/auction/domain/auction/repository/support/AuctionCriteriaRepository.java
  src/main/java/com/tasksprints/auction/domain/auction/repository/support/AuctionCriteriaRepositoryImpl.java
  src/main/java/com/tasksprints/auction/domain/auction/service/AuctionService.java
  src/main/java/com/tasksprints/auction/domain/auction/service/AuctionServiceImpl.java
  src/main/java/com/tasksprints/auction/domain/product/model/Product.java
  src/test/java/com/tasksprints/auction/api/AuctionControllerTest.java
  src/test/java/com/tasksprints/auction/domain/auction/repository/AuctionRepositoryTest.java
  src/test/java/com/tasksprints/auction/domain/auction/service/AuctionServiceImplTest.java
  src/test/java/com/tasksprints/auction/domain/product/ProductRepositoryTest.java
Labels: 기능 추가, 리팩토링 예정

#55 [FEATURE] Runner를 통한 AuctionInitializer
  gradlew
  src/main/java/com/tasksprints/auction/common/initializer/AuctionInitializer.java
Labels: 리팩토링 예정

#59 [FEATURE] - [WebSocket 기본 베이스 코드]
  build.gradle
  src/main/generated/com/tasksprints/auction/common/entity/QBaseEntity.java
  src/main/generated/com/tasksprints/auction/common/entity/QBaseEntityWithUpdate.java
  src/main/generated/com/tasksprints/auction/domain/auction/model/QAuction.java
  src/main/generated/com/tasksprints/auction/domain/bid/model/QBid.java
  src/main/generated/com/tasksprints/auction/domain/product/model/QProduct.java
  src/main/generated/com/tasksprints/auction/domain/product/model/QProductImage.java
  src/main/generated/com/tasksprints/auction/domain/review/model/QReview.java
  src/main/generated/com/tasksprints/auction/domain/socket/model/QChatRoom.java
  src/main/generated/com/tasksprints/auction/domain/socket/model/QChatter.java
  src/main/generated/com/tasksprints/auction/domain/user/model/QUser.java
  src/main/java/com/tasksprints/auction/AuctionApplication.java
  src/main/java/com/tasksprints/auction/api/bid/BidController.java
  src/main/java/com/tasksprints/auction/api/socket/ChatController.java
  src/main/java/com/tasksprints/auction/api/socket/ChatRoomController.java
  src/main/java/com/tasksprints/auction/common/config/JpaAuditingConfig.java
  src/main/java/com/tasksprints/auction/common/config/WebConfig.java
  src/main/java/com/tasksprints/auction/common/config/WebSockConfig.java
  src/main/java/com/tasksprints/auction/domain/bid/dto/BidResponse.java
  src/main/java/com/tasksprints/auction/domain/bid/model/Bid.java
  src/main/java/com/tasksprints/auction/domain/bid/repository/BidRepository.java
  src/main/java/com/tasksprints/auction/domain/bid/service/BidService.java
  src/main/java/com/tasksprints/auction/domain/bid/service/BidServiceImpl.java
  src/main/java/com/tasksprints/auction/domain/socket/dto/AddChatRoomDto.java
  src/main/java/com/tasksprints/auction/domain/socket/dto/MessageDto.java
  src/main/java/com/tasksprints/auction/domain/socket/model/ChatRoom.java
  src/main/java/com/tasksprints/auction/domain/socket/model/Chatter.java
  src/main/java/com/tasksprints/auction/domain/socket/repository/ChatRoomRepository.java
  src/main/java/com/tasksprints/auction/domain/socket/repository/ChatterRepository.java
  src/main/java/com/tasksprints/auction/domain/socket/service/ChatService.java
  src/main/java/com/tasksprints/auction/domain/user/model/User.java
  src/main/resources/application.yml
  src/main/resources/templates/chat/enter.html
  src/main/resources/templates/chat/room.html
Labels: 기능 추가
