Repository TaskSprints/auction, pull requests merged in 2024-12, with the labels that each got.

#76 [FEATURE] - [경매 종료 시 채팅 금지 기능]
  src/main/generated/com/tasksprints/auction/domain/chat/model/QChatRoom.java
  src/main/generated/com/tasksprints/auction/domain/socket/model/QChatRoom.java
  src/main/generated/com/tasksprints/auction/domain/socket/model/QChatter.java
  src/main/java/com/tasksprints/auction/api/auction/AuctionController.java
  src/main/java/com/tasksprints/auction/api/bid/BidController.java
  src/main/java/com/tasksprints/auction/api/chat/ChatController.java
  src/main/java/com/tasksprints/auction/api/chat/ChatRoomController.java
  src/main/java/com/tasksprints/auction/api/socket/ChatController.java
  src/main/java/com/tasksprints/auction/api/socket/ChatRoomController.java
  src/main/java/com/tasksprints/auction/common/config/WebSockConfig.java
  src/main/java/com/tasksprints/auction/domain/bid/dto/BidRequest.java
  src/main/java/com/tasksprints/auction/domain/bid/service/BidService.java
  src/main/java/com/tasksprints/auction/domain/bid/service/BidServiceImpl.java
  src/main/java/com/tasksprints/auction/domain/chat/dto/AddChatRoomDto.java
  src/main/java/com/tasksprints/auction/domain/chat/dto/MessageDto.java
  src/main/java/com/tasksprints/auction/domain/chat/dto/WhisperDto.java
  src/main/java/com/tasksprints/auction/domain/chat/model/ChatRoom.java
  src/main/java/com/tasksprints/auction/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/tasksprints/auction/domain/chat/service/ChatService.java
  src/main/java/com/tasksprints/auction/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/tasksprints/auction/domain/socket/model/Chatter.java
  src/main/java/com/tasksprints/auction/domain/socket/repository/ChatterRepository.java
  src/main/java/com/tasksprints/auction/domain/user/service/UserService.java
  src/main/java/com/tasksprints/auction/domain/user/service/UserServiceImpl.java
  src/main/resources/templates/chat/enter.html
  src/main/resources/templates/chat/room.html
  src/test/java/com/tasksprints/auction/api/AuctionControllerTest.java
  src/test/java/com/tasksprints/auction/api/BidControllerTest.java
Labels: 리팩토링 완료

#61 [FEATURE] : JWT 토큰 생성 및 검증
  .gitignore
  build.gradle
  src/main/java/com/tasksprints/auction/common/config/ClockConfig.java
  src/main/java/com/tasksprints/auction/common/jwt/JwtProperties.java
  src/main/java/com/tasksprints/auction/common/jwt/JwtProvider.java
  src/main/java/com/tasksprints/auction/common/jwt/JwtUtil.java
  src/main/java/com/tasksprints/auction/common/jwt/dto/response/JwtResponse.java
  src/main/java/com/tasksprints/auction/common/util/TimeUtil.java
  src/main/java/com/tasksprints/auction/domain/user/model/UserRole.java
  src/main/resources/application.yml
  src/test/java/com/tasksprints/auction/common/jwt/JwtProviderTest.java
  src/test/java/com/tasksprints/auction/common/util/TimeUtilTest.java
Labels: 기능 추가

#62 [FEATURE] : 토스페이먼츠 결제 API를 구현합니다.
  .gitignore
  src/main/java/com/tasksprints/auction/AuctionApplication.java
  src/main/java/com/tasksprints/auction/api/payment/PaymentController.java
  src/main/java/com/tasksprints/auction/api/wallet/WalletController.java
  src/main/java/com/tasksprints/auction/common/config/HttpClientConfig.java
  src/main/java/com/tasksprints/auction/common/constant/ApiResponseMessages.java
  src/main/java/com/tasksprints/auction/common/handler/GlobalExceptionHandler.java
  src/main/java/com/tasksprints/auction/common/initializer/AuctionInitializer.java
  src/main/java/com/tasksprints/auction/common/properties/PaymentProperties.java
  src/main/java/com/tasksprints/auction/domain/auction/model/Auction.java
  src/main/java/com/tasksprints/auction/domain/auction/repository/support/AuctionCriteriaRepositoryImpl.java
  src/main/java/com/tasksprints/auction/domain/payment/api/Response.java
  src/main/java/com/tasksprints/auction/domain/payment/client/ClientWrapper.java
  src/main/java/com/tasksprints/auction/domain/payment/client/HttpClientWrapper.java
  src/main/java/com/tasksprints/auction/domain/payment/client/PaymentApiSerializer.java
  src/main/java/com/tasksprints/auction/domain/payment/client/TossPaymentImpl.java
  src/main/java/com/tasksprints/auction/domain/payment/dto/request/PaymentRequest.java
  src/main/java/com/tasksprints/auction/domain/payment/dto/response/PaymentErrorResponse.java
  src/main/java/com/tasksprints/auction/domain/payment/dto/response/PaymentResponse.java
  src/main/java/com/tasksprints/auction/domain/payment/exception/InvalidSessionException.java
  src/main/java/com/tasksprints/auction/domain/payment/exception/PaymentDataMismatchException.java
  src/main/java/com/tasksprints/auction/domain/payment/exception/PaymentUserNotFoundException.java
  src/main/java/com/tasksprints/auction/domain/payment/model/PayStatus.java
  src/main/java/com/tasksprints/auction/domain/payment/model/PayType.java
  src/main/java/com/tasksprints/auction/domain/payment/model/Payment.java
  src/main/java/com/tasksprints/auction/domain/payment/repository/PaymentRepository.java
  src/main/java/com/tasksprints/auction/domain/payment/service/PaymentService.java
  src/main/java/com/tasksprints/auction/domain/payment/service/PaymentServiceImpl.java
  src/main/java/com/tasksprints/auction/domain/user/dto/response/UserDetailResponse.java
  src/main/java/com/tasksprints/auction/domain/user/model/User.java
  src/main/java/com/tasksprints/auction/domain/user/service/UserService.java
  src/main/java/com/tasksprints/auction/domain/user/service/UserServiceImpl.java
  src/main/java/com/tasksprints/auction/domain/wallet/exception/InSufficientBalanceException.java
  src/main/java/com/tasksprints/auction/domain/wallet/exception/WalletCreationException.java
  src/main/java/com/tasksprints/auction/domain/wallet/exception/WalletNotFoundException.java
  src/main/java/com/tasksprints/auction/domain/wallet/model/Wallet.java
  src/main/java/com/tasksprints/auction/domain/wallet/repository/WalletRepository.java
  src/main/java/com/tasksprints/auction/domain/wallet/service/WalletService.java
  src/main/java/com/tasksprints/auction/domain/wallet/service/WalletServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/templates/test.html
  src/test/java/com/tasksprints/auction/api/PaymentControllerTest.java
  src/test/java/com/tasksprints/auction/api/UserControllerTest.java
  src/test/java/com/tasksprints/auction/domain/payment/client/ClientWrapperTest.java
  src/test/java/com/tasksprints/auction/domain/payment/client/TossPaymentImplTest.java
  src/test/java/com/tasksprints/auction/domain/payment/repository/PaymentRepositoryTest.java
  src/test/java/com/tasksprints/auction/domain/payment/service/PaymentServiceImplTest.java
  src/test/java/com/tasksprints/auction/domain/user/UserServiceImplTest.java
  src/test/java/com/tasksprints/auction/domain/wallet/repository/WalletRepositoryTest.java
  src/test/java/com/tasksprints/auction/domain/wallet/service/WalletServiceImplTest.java
Labels: 리팩토링 요청, 개선 완료

#68 [FEATURE] 인증 인가 전반적인 구현을 완료합니다
  src/main/java/com/tasksprints/auction/api/auth/AuthController.java
  src/main/java/com/tasksprints/auction/common/config/JwtConfig.java
  src/main/java/com/tasksprints/auction/common/config/WebConfig.java
  src/main/java/com/tasksprints/auction/common/constant/ApiResponseMessages.java
  src/main/java/com/tasksprints/auction/common/handler/GlobalExceptionHandler.java
  src/main/java/com/tasksprints/auction/common/jwt/Auth.java
  src/main/java/com/tasksprints/auction/common/jwt/JwtProperties.java
  src/main/java/com/tasksprints/auction/common/jwt/JwtProvider.java
  src/main/java/com/tasksprints/auction/common/jwt/UserCheck.java
  src/main/java/com/tasksprints/auction/common/jwt/UserOnly.java
  src/main/java/com/tasksprints/auction/common/jwt/dto/response/JwtResponse.java
  src/main/java/com/tasksprints/auction/common/resolver/AuthenticationResolver.java
  src/main/java/com/tasksprints/auction/domain/auth/AccessTokenExtractor.java
  src/main/java/com/tasksprints/auction/domain/auth/TokenExtractor.java
  src/main/java/com/tasksprints/auction/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/tasksprints/auction/domain/auth/dto/response/AccessToken.java
  src/main/java/com/tasksprints/auction/domain/auth/dto/response/ResponseTokens.java
  src/main/java/com/tasksprints/auction/domain/auth/dto/response/UserTokens.java
  src/main/java/com/tasksprints/auction/domain/auth/exception/AccessTokenException.java
  src/main/java/com/tasksprints/auction/domain/auth/exception/AuthException.java
  src/main/java/com/tasksprints/auction/domain/auth/exception/RefreshTokenException.java
  src/main/java/com/tasksprints/auction/domain/auth/model/Accessor.java
  src/main/java/com/tasksprints/auction/domain/auth/model/RefreshToken.java
  src/main/java/com/tasksprints/auction/domain/auth/model/Role.java
  src/main/java/com/tasksprints/auction/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/tasksprints/auction/domain/auth/service/AuthService.java
  src/main/java/com/tasksprints/auction/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/tasksprints/auction/domain/auth/service/RefreshTokenCookieManager.java
  src/main/java/com/tasksprints/auction/domain/auth/service/RefreshTokenService.java
  src/main/java/com/tasksprints/auction/domain/auth/service/RefreshTokenServiceImpl.java
  src/main/java/com/tasksprints/auction/domain/user/model/UserRole.java
  src/main/java/com/tasksprints/auction/domain/user/repository/UserRepository.java
  src/main/java/com/tasksprints/auction/domain/user/service/UserService.java
  src/main/java/com/tasksprints/auction/domain/user/service/UserServiceImpl.java
  src/test/java/com/tasksprints/auction/api/AuctionControllerTest.java
  src/test/java/com/tasksprints/auction/api/AuthControllerTest.java
  src/test/java/com/tasksprints/auction/api/BaseControllerTest.java
  src/test/java/com/tasksprints/auction/api/ProductControllerTest.java
  src/test/java/com/tasksprints/auction/api/UserControllerTest.java
  src/test/java/com/tasksprints/auction/common/config/TestAuthConfig.java
  src/test/java/com/tasksprints/auction/common/jwt/JwtProviderTest.java
  src/test/java/com/tasksprints/auction/domain/auth/AccessTokenExtractorTest.java
  src/test/java/com/tasksprints/auction/domain/auth/repository/RefreshTokenRepositoryTest.java
  src/test/java/com/tasksprints/auction/domain/auth/service/AuthServiceImplTest.java
  src/test/java/com/tasksprints/auction/domain/auth/service/RefreshTokenCookieManagerTest.java
  src/test/java/com/tasksprints/auction/domain/auth/service/RefreshTokenServiceImplTest.java
  src/test/java/com/tasksprints/auction/domain/user/UserRepositoryTest.java
  src/test/java/com/tasksprints/auction/domain/user/UserServiceImplTest.java
Labels: 기능 추가
