Repository TaskSprints/auction, pull requests merged in 2024-09, with the labels that each got.

#21 [Refactor] ProductRepository 내부에 @Query 안써도 되는 것들 메소드형식으로 변경합니다
  src/main/java/com/tasksprints/auction/domain/product/repository/ProductRepository.java
  src/main/java/com/tasksprints/auction/domain/product/service/ProductServiceImpl.java
  src/test/java/com/tasksprints/auction/domain/product/ProductRepositoryTest.java
  src/test/java/com/tasksprints/auction/domain/product/ProductServiceImplTest.java
Labels: 개선 완료

#25 [ Docs ] Product Service requirement 추가
  docs/Product Service Requirement.md
Labels: 문서화, 진행중

#29 FEAT : 경매 유형이 [ ]인 경매 목록 조회 기능 추가
  .github/workflows/ci.yml
  src/main/java/com/tasksprints/auction/api/auction/AuctionController.java
  src/main/java/com/tasksprints/auction/domain/auction/dto/request/AuctionRequest.java
  src/main/java/com/tasksprints/auction/domain/auction/model/AuctionCategory.java
  src/main/java/com/tasksprints/auction/domain/auction/repository/AuctionRepository.java
  src/main/java/com/tasksprints/auction/domain/auction/repository/CustomAuctionRepositoryV1.java
  src/main/java/com/tasksprints/auction/domain/auction/service/AuctionService.java
  src/main/java/com/tasksprints/auction/domain/auction/service/AuctionServiceImpl.java
  src/test/java/com/tasksprints/auction/api/AuctionControllerTest.java
  src/test/java/com/tasksprints/auction/domain/auction/repository/AuctionRepositoryTest.java
  src/test/java/com/tasksprints/auction/domain/auction/service/AuctionServiceImplTest.java
Labels: 기능 추가

#34 [Refactor] QueryDSL 을 도입하여, 필터 기반의 조회를 수행합니다.
  build.gradle
  src/main/java/com/tasksprints/auction/api/auction/AuctionController.java
  src/main/java/com/tasksprints/auction/common/config/QueryDslConfig.java
  src/main/java/com/tasksprints/auction/domain/auction/dto/request/AuctionRequest.java
  src/main/java/com/tasksprints/auction/domain/auction/model/AuctionCategory.java
  src/main/java/com/tasksprints/auction/domain/auction/repository/AuctionCriteriaRepository.java
  src/main/java/com/tasksprints/auction/domain/auction/repository/AuctionCriteriaRepositoryImpl.java
  src/main/java/com/tasksprints/auction/domain/auction/repository/AuctionRepository.java
  src/main/java/com/tasksprints/auction/domain/auction/service/AuctionService.java
  src/main/java/com/tasksprints/auction/domain/auction/service/AuctionServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/tasksprints/auction/api/AuctionControllerTest.java
  src/test/java/com/tasksprints/auction/domain/auction/repository/AuctionRepositoryTest.java
  src/test/java/com/tasksprints/auction/domain/auction/service/AuctionServiceImplTest.java
  src/test/java/com/tasksprints/auction/domain/product/ProductRepositoryTest.java
  src/test/java/com/tasksprints/auction/domain/user/UserRepositoryTest.java
Labels: 해결 완료, 개선 완료, 기능 추가

#36 [ refactor ] 폴더 위치 변경 CustomRepository 위치 support 폴더로 위치 이동
  src/main/java/com/tasksprints/auction/domain/auction/repository/AuctionRepository.java
  src/main/java/com/tasksprints/auction/domain/auction/repository/support/AuctionCriteriaRepository.java
  src/main/java/com/tasksprints/auction/domain/auction/repository/support/AuctionCriteriaRepositoryImpl.java
Labels: 리팩토링 완료

#37 [FEATURE] : [경매 종료가 임박한 진행중인 경매 목록 조회]
  src/main/java/com/tasksprints/auction/api/auction/AuctionController.java
  src/main/java/com/tasksprints/auction/domain/auction/dto/request/AuctionRequest.java
  src/main/java/com/tasksprints/auction/domain/auction/model/AuctionStatus.java
  src/main/java/com/tasksprints/auction/domain/auction/repository/AuctionRepository.java
  src/main/java/com/tasksprints/auction/domain/auction/repository/support/AuctionCriteriaRepository.java
  src/main/java/com/tasksprints/auction/domain/auction/repository/support/AuctionCriteriaRepositoryImpl.java
  src/main/java/com/tasksprints/auction/domain/auction/service/AuctionService.java
  src/main/java/com/tasksprints/auction/domain/auction/service/AuctionServiceImpl.java
  src/test/java/com/tasksprints/auction/api/AuctionControllerTest.java
  src/test/java/com/tasksprints/auction/domain/auction/repository/AuctionRepositoryTest.java
  src/test/java/com/tasksprints/auction/domain/auction/service/AuctionServiceImplTest.java
Labels: 기능 추가, 도움 필요

#44 [FEATURE] : [Auction 도메인 필터 기반 검색 기능 추가]
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
  src/main/java/com/tasksprints/auction/api/auction/AuctionController.java
  src/main/java/com/tasksprints/auction/common/config/WebConfig.java
  src/main/java/com/tasksprints/auction/common/resolver/SearchConditionResolver.java
  src/main/java/com/tasksprints/auction/domain/auction/dto/request/AuctionRequest.java
  src/main/java/com/tasksprints/auction/domain/auction/model/Auction.java
  src/main/java/com/tasksprints/auction/domain/auction/model/AuctionStatus.java
  src/main/java/com/tasksprints/auction/domain/auction/repository/AuctionRepository.java
  src/main/java/com/tasksprints/auction/domain/auction/repository/CustomAuctionRepositoryV1.java
  src/main/java/com/tasksprints/auction/domain/auction/repository/support/AuctionCriteriaRepository.java
  src/main/java/com/tasksprints/auction/domain/auction/repository/support/AuctionCriteriaRepositoryImpl.java
  src/main/java/com/tasksprints/auction/domain/auction/service/AuctionService.java
  src/main/java/com/tasksprints/auction/domain/auction/service/AuctionServiceImpl.java
  src/test/java/com/tasksprints/auction/api/AuctionControllerTest.java
  src/test/java/com/tasksprints/auction/domain/auction/repository/AuctionRepositoryTest.java
  src/test/java/com/tasksprints/auction/domain/auction/service/AuctionServiceImplTest.java
  src/test/java/com/tasksprints/auction/domain/product/ProductServiceImplTest.java
Labels: 기능 추가, 진행중, 리팩토링 예정

#47 chore : ci&cd pipeline (ssh 기반) workflow 구성
  .github/workflows/ci-cd.yml
Labels: 개선 완료

#48 Fix : ci&cd pipeline (ssh 기반) -> script 수정
  .github/workflows/ci-cd.yml
Labels: 개선 완료

#49 Fix : ci flow 내에 workflow formatter 확인 추가
  .github/workflows/ci-cd.yml
Labels: 개선 완료

#53 Feat : Cors Configuration 추가
  .github/workflows/ci-cd.yml
  src/main/java/com/tasksprints/auction/common/config/WebConfig.java
Labels: 개선 완료
